### PR TITLE
fix: styling of components

### LINKED ISSUE #42: bug: inline codeblocks don't have the correct background color
**Describe the bug**

The background color from inline codeblocks differ from Discord's.

**To Reproduce**

1. Add an inline codeblock.
2. See how the background color differs from Discord's.

**Expected behavior**

The background color is different in both light and dark theme.

**Screenshots**

Light Theme:

image
image

Dark Theme:

image
image

**Additional context**

cc: @iCrawl

### LINKED ISSUE #43: bug: codeblock text overflow on long lines
**Describe the bug**

Codeblock's code overflow.

**To Reproduce**

1. Make a codeblock.
2. Write a very long line.

**Expected behavior**

The line will be split, keeping itself inside the block.

**Screenshots**

image

**Additional context**

cc: @iCrawl

### PR DESCRIPTION
**Pull request by iCrawl**
This fixes a whole slew of CSS styling issues to get closer to Discords design philosophy.

Edit: I also took the liberty of copying out the settings and extensions to their own settings.json and extensions.json since I don't use Docker/Containers/Codespaces to work on this.

closes #42
closes #43

Old:
image

New:
image

Old:
image

New:
image

Old:
image

New:
image

Old:
image

New:
image

Old:
image

New:
image

### CODE REVIEW

File: packages/core/src/components/discord-embed/discord-embed.tsx [hunk 1]
```diff
@@ -145,7 +145,11 @@ export class DiscordEmbed implements ComponentInterface {
 								<slot></slot>
 							</div>
 							<slot name="fields"></slot>
-							<div class={clsx('discord-embed-media', { 'discord-embed-media-video': Boolean(this.video) })}>{this.renderMedia()}</div>
+							{this.image || this.video ? (
```
Comment (kyranet) [inline packages/core/src/components/discord-embed/discord-embed.tsx:148]: Does this execute as `(this.image || this.video) ? (...) : null` or as `this.image || (this.video ? (...) : null)`?

If ESLint doesn't complain, I think it might be worth to wrap the OR condition with parens.

**Review by kyranet — COMMENTED** [review]
The changes look good, not sure about the `.devcontainer` changes, but if this PR is tested in both PC and tablet/phone, it LGTM.

File: packages/core/src/components/discord-embed/discord-embed.tsx (hunk 1 above)
Comment (iCrawl) [reply packages/core/src/components/discord-embed/discord-embed.tsx:148]: This executes as the former based on comparison operations.

Prettier does complain however, so I think we are on the safe side with this:
image

**Comment by iCrawl** [comment]
Devcontainer was not touched, I simply pulled out the settings and extensions so they are also applied when not using a container.

**Review by kyranet — APPROVED** [review]

File: .vscode/extensions.json [hunk 2]
```diff
@@ -0,0 +1,19 @@
+{
```
Comment (Favna) [inline .vscode/extensions.json:1]: Please remove this file and `.vscode/settings.json`. While they're not bad per se, it's just not something we really add in Skyra Project repos.

**Review by Favna — CHANGES_REQUESTED** [review]
Other than this it LGTM.

Should note btw that before I can release it I need to dive into the lib again because before my holiday late march I was struggling with something that was broken, but I don't remember what it was. That's also why the latest version is `2.0.3-alpha.0`, because yarn link was being a huge PITA at that time.

File: .vscode/extensions.json (hunk 2 above)
Comment (iCrawl) [reply .vscode/extensions.json:1]: Yeah, I can do that. I mentioned it briefly to @kyranet though, so maybe you can find some nice solution for this overall.

> If I would have coded this with Codespaces, it would have used his .devcontainer settings and forced it on me this way
> I only added it since there is stuff like import sorting in there, which is kind of a source changing thing and will cause a conflict when you would re-save the file having those options enabled on your local settings

Comment (Favna) [reply .vscode/extensions.json]: You're not wrong. So far this hasn't been an issue though, so for now lets just revert it.

Comment (iCrawl) [reply .vscode/extensions.json]: Removed all unrelated changes 👍

**Review by Favna — APPROVED** [review]
